pip install discord.py-self
pip install pyPrivnote
pip install names
pip install simplejson
pip install aiohttp
pip install colour
pip install termcolour
pip install Faker
pip install plyer
pip install sty
pip install colorama
pip install discord-rpc.py
pip install requests
pip install uwuify
pip install numpy
pip install discum
pip install discord-webhook
pip install random_user_agent
pip install gputil
pip install psutil
pip install pillow
pip install pygame
pip install sounddevice
pip install discord-emoji
pip install pync
pip install WMI